// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABlLXhcDSTROvjeRaZMPNARjddx3-xtt8',
    appId: '1:9908550140:web:96a544b534e281095b9a79',
    messagingSenderId: '9908550140',
    projectId: 'fir-login-template-e4400',
    authDomain: 'fir-login-template-e4400.firebaseapp.com',
    storageBucket: 'fir-login-template-e4400.appspot.com',
    measurementId: 'G-04HNELWK09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGDuuXdjW6ieDdfbMg-2w4q5ug7rK6PC8',
    appId: '1:9908550140:android:8efe6a4952b442f65b9a79',
    messagingSenderId: '9908550140',
    projectId: 'fir-login-template-e4400',
    storageBucket: 'fir-login-template-e4400.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxVszqJGXnY5pnh4lqkgFj0qQnzuQ2siw',
    appId: '1:9908550140:ios:a312ec57ad6e52be5b9a79',
    messagingSenderId: '9908550140',
    projectId: 'fir-login-template-e4400',
    storageBucket: 'fir-login-template-e4400.appspot.com',
    iosClientId: '9908550140-qll6nmpi58922v118jhb4sdgn30brhqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.vertexFbAuthTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxVszqJGXnY5pnh4lqkgFj0qQnzuQ2siw',
    appId: '1:9908550140:ios:f67e9e8700fd2cbb5b9a79',
    messagingSenderId: '9908550140',
    projectId: 'fir-login-template-e4400',
    storageBucket: 'fir-login-template-e4400.appspot.com',
    iosClientId: '9908550140-b6818tate30kh0unn1s0dgvijcnbmmhh.apps.googleusercontent.com',
    iosBundleId: 'com.example.vertexFbAuthTemplate.RunnerTests',
  );
}
